#ifndef VEHICLE_LIMITS_H
#define VEHICLE_LIMITS_H

#define VEHICLE_MAX_SPEED_KMH 40.0f
#define VEHICLE_MAX_TORQUE_NM 12.0f
#define THROTTLE_DEADBAND 0.03f
#define BRAKE_OVERRIDE_THRESHOLD 0.10f
#define MAX_CAN_TIMEOUT_MS 200u
#define MAX_BMS_TIMEOUT_MS 500u

#endif
